# Generated by Django 4.2.4 on 2023-08-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='_id',
            new_name='id',
        ),
    ]
