# Generated by Django 4.2.4 on 2023-08-21 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='contacts',
        ),
        migrations.AddField(
            model_name='appuser',
            name='contacts',
            field=models.ManyToManyField(through='user.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
