# Generated by Django 4.2.4 on 2023-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_appuser_contacts_remove_appuser_moves_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
